apiVersion: v1
kind: Service
metadata:
  name: oauth-test
  labels:
    app.kubernetes.io/instance: oauth-test
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: oauth-test
    app.kubernetes.io/version: master
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30800
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: oauth-test
    app.kubernetes.io/name: oauth-test
